const assert = require('assert');
const { convertPrettyToJsonl } = require('../out/jsonl/utils');

// Empty content stays empty
assert.strictEqual(convertPrettyToJsonl(''), '');
assert.strictEqual(convertPrettyToJsonl('   \n  \n'), '');

// Single pretty-printed object becomes one compact line
assert.strictEqual(
    convertPrettyToJsonl('{\n  "name": "alpha",\n  "value": 1\n}'),
    '{"name":"alpha","value":1}'
);

// Multiple pretty-printed objects (as generated by the Pretty Print view)
const pretty = [
    '{',
    '  "name": "alpha",',
    '  "value": 1',
    '}',
    '{',
    '  "name": "beta",',
    '  "nested": {',
    '    "deep": [1, 2, 3]',
    '  }',
    '}'
].join('\n');
assert.strictEqual(
    convertPrettyToJsonl(pretty),
    '{"name":"alpha","value":1}\n{"name":"beta","nested":{"deep":[1,2,3]}}'
);

// Blank lines between objects are tolerated
assert.strictEqual(
    convertPrettyToJsonl('{\n  "a": 1\n}\n\n{\n  "b": 2\n}\n'),
    '{"a":1}\n{"b":2}'
);

// Braces and quotes inside strings do not confuse the parser
assert.strictEqual(
    convertPrettyToJsonl('{\n  "text": "curly } brace [ and \\" quote"\n}'),
    '{"text":"curly } brace [ and \\" quote"}'
);

// Top-level arrays and scalars are preserved as their own lines
assert.strictEqual(
    convertPrettyToJsonl('[\n  1,\n  2\n]\n"hello"\n42\ntrue\nnull'),
    '[1,2]\n"hello"\n42\ntrue\nnull'
);

// Already-compact JSONL passes through unchanged
assert.strictEqual(
    convertPrettyToJsonl('{"a":1}\n{"b":2}'),
    '{"a":1}\n{"b":2}'
);

// Invalid / mid-edit content returns null instead of dropping rows
assert.strictEqual(convertPrettyToJsonl('{\n  "a": 1\n'), null);
assert.strictEqual(convertPrettyToJsonl('{\n  "a": 1,\n}'), null);
assert.strictEqual(convertPrettyToJsonl('{\n  "a": 1\n}\ngarbage'), null);
assert.strictEqual(convertPrettyToJsonl('{\n  "a": "unterminated\n}'), null);

console.log('prettyToJsonl tests passed');
