// Approximate real VS Code default theme token values (Dark Modern / Light Modern),
// used to render the webview's own CSS (which consumes --vscode-* custom properties)
// authentically outside of a real VS Code host.
const dark = {
  'editor-background': '#1e1e1e',
  'foreground': '#cccccc',
  'font-family': "-apple-system, BlinkMacSystemFont, 'Segoe WPC', 'Segoe UI', system-ui, 'Ubuntu', 'Droid Sans', sans-serif",
  'editor-font-family': "'SF Mono', Monaco, Menlo, Consolas, 'Ubuntu Mono', monospace",
  'font-size': '13px',
  'input-background': '#3c3c3c',
  'input-border': '#3c3c3c',
  'input-foreground': '#cccccc',
  'input-placeholderForeground': '#a6a6a6',
  'dropdown-background': '#3c3c3c',
  'dropdown-border': '#3c3c3c',
  'button-background': '#0e639c',
  'button-foreground': '#ffffff',
  'button-hoverBackground': '#1177bb',
  'button-secondaryBackground': '#3a3d41',
  'button-secondaryForeground': '#ffffff',
  'button-secondaryBorder': '#3a3d41',
  'button-secondaryHoverBackground': '#45494e',
  'list-activeSelectionBackground': '#04395e',
  'list-activeSelectionForeground': '#ffffff',
  'list-hoverBackground': '#2a2d2e',
  'list-inactiveSelectionBackground': '#37373d',
  'panel-border': '#454545',
  'focusBorder': '#007fd4',
  'badge-background': '#4d4d4d',
  'badge-foreground': '#ffffff',
  'editorWidget-background': '#252526',
  'editorWidget-border': '#454545',
  'editorHoverWidget-background': '#252526',
  'editorHoverWidget-foreground': '#cccccc',
  'editorHoverWidget-border': '#454545',
  'menu-background': '#252526',
  'menu-foreground': '#cccccc',
  'menu-selectionBackground': '#04395e',
  'menu-separatorBackground': '#454545',
  'menu-border': '#454545',
  'notifications-background': '#252526',
  'notifications-border': '#474747',
  'notifications-foreground': '#cccccc',
  'textLink-foreground': '#3794ff',
  'textPreformat-foreground': '#d7ba7d',
  'textCodeBlock-background': '#0a0a0a',
  'textBlockQuote-background': 'rgba(127,127,127,0.1)',
  'textBlockQuote-border': 'rgba(0,122,204,0.5)',
  'descriptionForeground': '#9d9d9d',
  'disabledForeground': 'rgba(204,204,204,0.5)',
  'errorForeground': '#f48771',
  'icon-foreground': '#cccccc',
  'toolbar-hoverBackground': 'rgba(90,93,94,0.31)',
  'inputOption-activeBackground': 'rgba(0,127,212,0.4)',
  'inputOption-activeBorder': '#007acc',
  'inputOption-activeForeground': '#ffffff',
  'editor-findMatchBackground': '#515c6a',
  'editor-findMatchBorder': '#74879b',
  'editor-findMatchHighlightBackground': 'rgba(234,92,0,0.33)',
};

const light = {
  'editor-background': '#ffffff',
  'foreground': '#3b3b3b',
  'font-family': dark['font-family'],
  'editor-font-family': dark['editor-font-family'],
  'font-size': '13px',
  'input-background': '#ffffff',
  'input-border': '#cecece',
  'input-foreground': '#3b3b3b',
  'input-placeholderForeground': '#767676',
  'dropdown-background': '#ffffff',
  'dropdown-border': '#cecece',
  'button-background': '#007acc',
  'button-foreground': '#ffffff',
  'button-hoverBackground': '#0062a3',
  'button-secondaryBackground': '#e5e5e5',
  'button-secondaryForeground': '#3b3b3b',
  'button-secondaryBorder': '#e5e5e5',
  'button-secondaryHoverBackground': '#cccccc',
  'list-activeSelectionBackground': '#e8e8e8',
  'list-activeSelectionForeground': '#000000',
  'list-hoverBackground': '#f0f0f0',
  'list-inactiveSelectionBackground': '#e4e6f1',
  'panel-border': '#e5e5e5',
  'focusBorder': '#005fb8',
  'badge-background': '#005fb8',
  'badge-foreground': '#ffffff',
  'editorWidget-background': '#f8f8f8',
  'editorWidget-border': '#e5e5e5',
  'editorHoverWidget-background': '#f8f8f8',
  'editorHoverWidget-foreground': '#3b3b3b',
  'editorHoverWidget-border': '#e5e5e5',
  'menu-background': '#ffffff',
  'menu-foreground': '#3b3b3b',
  'menu-selectionBackground': '#e8e8e8',
  'menu-separatorBackground': '#e5e5e5',
  'menu-border': '#e5e5e5',
  'notifications-background': '#f8f8f8',
  'notifications-border': '#e5e5e5',
  'notifications-foreground': '#3b3b3b',
  'textLink-foreground': '#005fb8',
  'textPreformat-foreground': '#a31515',
  'textCodeBlock-background': '#f5f5f5',
  'textBlockQuote-background': 'rgba(127,127,127,0.1)',
  'textBlockQuote-border': 'rgba(0,90,190,0.5)',
  'descriptionForeground': '#6b6b6b',
  'disabledForeground': 'rgba(59,59,59,0.5)',
  'errorForeground': '#a1260d',
  'icon-foreground': '#424242',
  'toolbar-hoverBackground': 'rgba(184,184,184,0.31)',
  'inputOption-activeBackground': 'rgba(0,95,184,0.2)',
  'inputOption-activeBorder': '#005fb8',
  'inputOption-activeForeground': '#000000',
  'editor-findMatchBackground': '#a8ac94',
  'editor-findMatchBorder': '#9e9e9e',
  'editor-findMatchHighlightBackground': 'rgba(234,92,0,0.33)',
};

// Outer VS Code chrome (tab strip + breadcrumb), not part of the webview itself,
// added only so screenshots read as "inside VS Code" like a real editor window.
const chrome = {
  dark: {
    tabsBg: '#252526',
    tabActiveBg: '#1e1e1e',
    tabActiveFg: '#ffffff',
    tabBorder: '#00000000',
    breadcrumbBg: '#1e1e1e',
    breadcrumbFg: '#b3b3b3',
    iconFg: '#c5c5c5',
  },
  light: {
    tabsBg: '#f3f3f3',
    tabActiveBg: '#ffffff',
    tabActiveFg: '#333333',
    tabBorder: '#00000000',
    breadcrumbBg: '#ffffff',
    breadcrumbFg: '#6b6b6b',
    iconFg: '#424242',
  },
};

function cssVars(theme) {
  return Object.entries(theme).map(([k, v]) => `--vscode-${k}: ${v};`).join('\n');
}

module.exports = { dark, light, chrome, cssVars };
